### ISSUE TITLE
[question] Multisensor not discovering all values

### ISSUE THREAD

**Issue by chilicheech** [OpenZWave/Zwave2Mqtt#232] opened 2020-02-02 23:06 UTC
I have 2 different multisensors that have temperature, humidity, luminance, and motion sensing. All values are identified properly and I can see them in the UI. However, the hass devices section only shows:
- binary_sensor_contact
- sensor_battery
- sensor_humidity
- sensor_illuminance
- sensor_temperature

The devices that are missing in hass devices are:
- sensor_home_security/sensor_security/sensor_burglar
- sensor_alarm_type
- sensor_alarm_level

The missing sensors are the ones used for motion and tamper detection.

I see that the configurations exist here: https://github.com/OpenZWave/Zwave2Mqtt/blob/v2.1.1/hass/configurations.js#L135-L158

I also see some definition/discovery here: https://github.com/OpenZWave/Zwave2Mqtt/blob/v2.1.1/lib/Gateway.js#L785-L802

I don't understand why the hass devices are not being created. Here are some screenshots:

Sensor 1 - ZSE40 4-in-1 sensor (Zooz)
<img width="230" alt="Screen Shot 2020-02-02 at 3 03 29 PM" src="https://user-images.githubusercontent.com/732659/73616830-33ecf180-45cd-11ea-9e55-810ad8a6b1a7.png">
<img width="741" alt="Screen Shot 2020-02-02 at 3 04 05 PM" src="https://user-images.githubusercontent.com/732659/73616835-4535fe00-45cd-11ea-9c66-8aa59b46a97b.png">

Sensor 2 - ZP3111 Multisensor 4in1 (Vision Security)
<img width="223" alt="Screen Shot 2020-02-02 at 3 04 53 PM" src="https://user-images.githubusercontent.com/732659/73616842-626acc80-45cd-11ea-87cb-b1eb7d917b53.png">
<img width="742" alt="Screen Shot 2020-02-02 at 3 05 17 PM" src="https://user-images.githubusercontent.com/732659/73616848-7a425080-45cd-11ea-8f00-c2f4c56ba70d.png">

My question is, how can I get the other values to show up as hass devices?

Cheers,

**Comment by robertsLando** [comment] 2020-02-03 08:10
@chilicheech The problem is that they have valueID index:

113: Command class alarm
1: Instance
512 513 7 256: The valueID index

I use command classes and index to identify devices, as you can see the alarm class I only handle index 0 1 and 10 https://github.com/OpenZWave/Zwave2Mqtt/blob/v2.1.1/lib/Gateway.js#L785-L802 . I think your device doesn't respect ozw specs (usually alarm level should be 1, alarm type 0 and the alarm_burglar 10)

**Comment by robertsLando** [comment] 2020-02-03 08:18
@chilicheech Fixed now, check latest commit :)

**Closed** 2020-02-03 08:18 UTC
Labels: question

**Comment by chilicheech** [comment] 2020-02-03 21:09
Thank you so much for the quick fix :)

**Comment by chilicheech** [comment] 2020-02-03 21:36
@robertsLando quick question. I want to build the docker image so i can test the new change locally so I'm looking at this: https://github.com/robertsLando/Zwave2Mqtt-docker#custom-builds
So, looking at the Dockerfile, i see this: https://github.com/robertsLando/Zwave2Mqtt-docker/blob/master/Dockerfile#L9 and it says: `# Latest stable 1.4`
Is that still the case? I thought we were defaulting to 1.6 now? If it's still defaulting to 1.4, what sha should I use for 1.6?

**Comment by robertsLando** [comment] 2020-02-03 21:53
I suggest you to build it also by replacing the openzwave sha with latest ozw commit so you are also using latest ozw in your docker. 

So copy and paste there the ozw and the z2m latest commit sha and your image will be ready

Daniel

**Comment by chilicheech** [comment] 2020-02-04 03:19
Just reporting back that it's working great. Thanks again:
<img width="738" alt="Screen Shot 2020-02-03 at 7 19 12 PM" src="https://user-images.githubusercontent.com/732659/73710922-25c8cf00-46ba-11ea-8ef7-bb068f80bd56.png">

**Comment by chilicheech** [comment] 2020-02-04 03:38
@robertsLando another question, since in openzwave the value is called `home security` do you think it would make sense to label this `home_security` instead of `alarm_burglar`? Or maybe `alarm_home_security`? I found a reference doc here: https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/ValueIDIndexesDefines.def#L1076 and here: https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/ValueIDIndexesDefines.h#L9
If so, I'll be happy to send you a PR to relabel it..

**Comment by Dinth** [comment] 2020-02-04 08:12
The next release is gonna be soo great :)

**Comment by robertsLando** [comment] 2020-02-04 09:18
@chilicheech I have follow this file specs: https://github.com/OpenZWave/open-zwave/blob/master/config/Localization.xml

Anyway there are 18 different types of alarms (index < 256) would you mind to create a configuration for each one of them? Every configuration need also to be added to /hass/configurations.js

**Comment by chilicheech** [comment] 2020-02-04 17:12
Sounds good. I'll work on that today.
