### ISSUE TITLE
[bug] Error, ERROR: Not enough space in stream buffer

### ISSUE THREAD

**Issue by ksuclipse** [OpenZWave/Zwave2Mqtt#141] opened 2019-10-13 01:44 UTC
**Version**

Build/Run method
- [ X] Docker
- [ ] PKG
- [ X] Manually built (git clone - npm install - npm run build ) - manually build docker image 

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.4.1

**Describe the bug**
after docker is running for a while (at least a day) i start to get many errors of Error, ERROR: Not enough space in stream buffer.  This is solved by restarting the container.  when this happens nothing talks on the zwave network.

**To Reproduce**
run docker for more than a day

**Expected behavior**
Not this

**Additional context**
Running commit: 85b49dcf00c3efdb3825e42d93b265052a9f58a6

**Comment by robertsLando** [comment] 2019-10-13 07:20
Could you append log output? 

Daniel

**Comment by Fishwaldo** [comment] 2019-10-14 03:11
This is usually seen on rPI or SBC boards with a Z-Stick. Using a USB powered hub usually resolves it. 

(It’s probably related to the recently discovered incompatibilities discovered on rPI 4 boards. )

**Comment by robertsLando** [comment] 2019-10-22 06:19
@ksuclipse Can I close this? Did you resolved your issue?

**Comment by ksuclipse** [comment] 2019-10-26 03:57
yes not sure what happened but after recent pull its gone

**Comment by ksuclipse** [comment] 2019-10-28 03:09
Happened again unfortunately.  any thoughts?

[OZW_Log.txt](https://github.com/OpenZWave/Zwave2Mqtt/files/3776961/OZW_Log.txt)

**Comment by ksuclipse** [comment] 2019-10-28 03:09
@robertsLando

**Comment by robertsLando** [comment] 2019-11-14 17:02
@Fishwaldo could you check this?

**Comment by ksuclipse** [comment] 2019-12-01 05:50
any ideas on this?  seems to happen after several days of uptime.  about to pull the newest commit so i'll keep you posted as well

**Comment by Fishwaldo** [comment] 2019-12-01 06:23
See my comment above. It’s a hardware/kernel issue and not anything in OZW we can fix.  Try a powered hub. Most reporters say they fix the issue.

**Comment by ksuclipse** [comment] 2019-12-01 06:30
I’m directly connected to the nuc running it. Is there a better zwave stick I should be using??

**Comment by johntdyer** [comment] 2019-12-11 21:08
I just started getting this as well on Home Assistant 0.102

**Comment by Fishwaldo** [comment] 2019-12-12 05:38
As already mentioned this is in most cases related to power issues with the USB port. Using a powered USB hub solves it most of the time.

**Comment by ksuclipse** [comment] 2019-12-12 06:02
In my case at least it is directly connected to the board. Are you saying I
should put a powered hub in between the pc and the zwave receiver??

**Comment by Fishwaldo** [comment] 2019-12-12 06:15
Yes.

**Comment by robertsLando** [comment] 2019-12-12 06:38
Just curious, is this problem also present when using aeotec z-stick usb gen5?

Daniel

**Comment by Fishwaldo** [comment] 2019-12-12 07:53
yes - basically internally all sticks are the same... it affects most of them.

**Comment by robertsLando** [comment] 2019-12-12 08:47
But why this happens with ozw 1.6 and not 1.4??

Daniel

**Comment by Fishwaldo** [comment] 2019-12-12 08:49
Its happened since 1.0

 

It’s a hardware issue…

**Comment by nellering** [comment] 2019-12-13 01:47
I just wanted to mention that I am getting this with an  aeotec z-stick usb gen5 directly pluged into a Gigabyte 630M motherboard.  I will also try a different port and pickup a powered usb hub to see if it fixes the issue.

**Comment by johntdyer** [comment] 2019-12-16 16:30
@Fishwaldo 
> It’s a hardware issue…

Its a hardware issue as in our zWave sticks are broken ?  Is there an upstream issue somewhere we can subscribe too  for updates ?

**Comment by nellering** [comment] 2019-12-19 00:32
I picked up an external powered USB hub, and I am still getting the buffer issue with my Aoetec Gen 5 plugged into the powered hub.

**Comment by riemers** [comment] 2019-12-28 14:11
While reading up on things, also issues i can also recall having seen this before a few times. Have not seen it anymore after i started playing more with it. But i have a Nuc with mains power to it. If i see the same stream logs again i'll paste it here too.

**Comment by riemers** [comment] 2019-12-28 19:45
```
OpenZWave Error, ERROR: Not enough space in stream buffer
OpenZWave Error, ERROR: Not enough space in stream buffer
OpenZWave Error, ERROR: Not enough space in stream buffer
OpenZWave Error, ERROR: Not enough space in stream buffer
```

Was trying to do a fresh install again. Docker logs showed this beforehand. This was without any current zwcfg file. 

```
2019-12-28 16:16:35.605 Detail, Node089, Notification: NodeQueriesComplete
2019-12-28T15:16:35.610Z z2m:Zwave node 88 ready: Unknown: id=0154 - Unknown: type=0100, id=0201 (Unknown)
2019-12-28 16:16:35.612 Detail, Node090, Query Stage Complete (Dynamic)
2019-12-28 16:16:35.612 Detail, Node090, AdvanceQueries queryPending=0 queryRetries=0 queryStage=Configuration live=1
2019-12-28 16:16:35.612 Detail, Node090, QueryStage_Configuration
2019-12-28 16:16:35.612 Detail, Node090, QueryStage_Complete
2019-12-28 16:16:35.612 Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
2019-12-28 16:16:35.612 Warning, CheckCompletedNodeQueries all=0, deadFound=1 sleepingOnly=0
2019-12-28 16:16:35.612 Detail, Node090, Notification: NodeQueriesComplete
2019-12-28 16:16:35.612 Detail, Node092, Query Stage Complete (Dynamic)
2019-12-28 16:16:35.612 Detail, Node092, AdvanceQueries queryPending=0 queryRetries=0 queryStage=Configuration live=1
2019-12-28 16:16:35.612 Detail, Node092, QueryStage_Configuration
2019-12-28 16:16:35.612 Detail, Node092, QueryStage_Complete
2019-12-28 16:16:35.612 Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
2019-12-28 16:16:35.612 Warning, CheckCompletedNodeQueries all=0, deadFound=1 sleepingOnly=0
2019-12-28 16:16:35.612 Info, Failed to load device_classes.xml
2019-12-28 16:16:35.612 Info, Check that the config path provided when creating the Manager points to the correct location.
2019-12-28 16:16:35.612 Detail, Node092, Notification: NodeQueriesComplete
2019-12-28T15:16:35.614Z z2m:Zwave node 89 ready: Unknown: id=0154 - Unknown: type=0100, id=0201 (Unknown)
2019-12-28 16:16:35.614 Info, Failed to load device_classes.xml
2019-12-28 16:16:35.614 Info, Check that the config path provided when creating the Manager points to the correct location.
2019-12-28T15:16:35.615Z z2m:Zwave node 90 ready: Unknown: id=0154 - Unknown: type=0100, id=0201 (Unknown)
2019-12-28 16:16:35.615 Detail, Node093, Query Stage Complete (Dynamic)
2019-12-28 16:16:35.615 Detail, Node093, AdvanceQueries queryPending=0 queryRetries=0 queryStage=Configuration live=1
2019-12-28 16:16:35.615 Detail, Node093, QueryStage_Configuration
2019-12-28 16:16:35.615 Detail, Node093, QueryStage_Complete
2019-12-28 16:16:35.615 Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
2019-12-28 16:16:35.617 Info, Failed to load device_classes.xml
2019-12-28 16:16:35.617 Info, Check that the config path provided when creating the Manager points to the correct location.
2019-12-28T15:16:35.618Z z2m:Zwave node 92 ready: Unknown: id=0154 - Unknown: type=0100, id=0201 (Unknown)
--- multiple http calls ---
2019-12-28 16:24:01.039 Error, ERROR: Not enough space in stream buffer
2019-12-28 16:24:02.039 Error, ERROR: Not enough space in stream buffer
2019-12-28 16:24:02.039 Error, ERROR: Not enough space in stream buffer
2019-12-28 16:24:02.039 Error, ERROR: Not enough space in stream buffer
2019-12-28 16:24:02.039 Error, ERROR: Not enough space in stream buffer
2019-12-28 16:24:02.039 Error, ERROR: Not enough space in stream buffer
2019-12-28 16:24:02.039 Error, ERROR: Not enough space in stream buffer
etc etc etc
```

**Comment by robertsLando** [comment] 2020-01-03 16:22
@Fishwaldo The problem seems still present after using a power hub

**Comment by robertsLando** [comment] 2020-01-29 07:54
@Fishwaldo When upgrading to OZW 1.6 I'm getting this problem too, also I'm getting segmentation fault when sending switch multilevel set commands. This was working befor in OZW 1.4

**Comment by Fishwaldo** [comment] 2020-01-29 08:46
The stream issue - it’s not a OZW issue. It’s the kernel running out of buffer space to transmit. It seems to be hardware based. I can’t do jack about that unless someone debuts the kernel/hardware. 

The multilevel crash is known. The bug was present in OZW 1.4 but it didn’t crash. The fix is very involved and will be what I’m working on soon. (2 attempts at a fix caused other issues).

**Closed** 2020-03-09 08:29 UTC
Labels: bug, lib problem

**Comment by hyperbolic2346** [comment] 2020-09-09 03:01
I'm hitting this as well and the WAF is painful. I originally hit this on a pi4 and found this issue. I tried a powered hub as well and no change. I then switched to a different machine, though low-power as well. Could this be related to the buffer defaulting to 2k and we fill that during high load?

https://github.com/OpenZWave/open-zwave/blob/f44387718c9f9509e410dc9c3e8be1aa2b0a5a74/cpp/src/platform/Controller.h#L67

I have no idea the message sizes we pass into this buffer or how many we can generate, but why not bump it and see if this disappears? Maybe add some metrics on the high water of the buffer?

**Comment by robertsLando** [comment] 2020-09-14 12:41
@hyperbolic2346 are you using latest version of z2m? docker or manually built? what ozw version are you using?

**Comment by hyperbolic2346** [comment] 2020-09-14 17:42
I'm using the latest z2m docker image. It says 1.6.1240 in the control panel. Should I make a new bug since this one was closed?

**Comment by robertsLando** [comment] 2020-09-15 06:23
@hyperbolic2346 I suggest to open this issue on ozw repo, it's not a bug with z2m
