### ISSUE TITLE
[bug] ZW100 MultiSensor Temperature Scale issue

### ISSUE THREAD

**Issue by iAutom8** [OpenZWave/Zwave2Mqtt#102] opened 2019-08-19 03:07 UTC
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: Latest Docker Image

**Issue**
I started using Zwave2Mqtt and has been working great but noticed that my  ZW100 (AEON  Labs MultiSensor 6) is set to report in Celsius but keep getting readings in Fahrenheit.  I noticed this is also true in Zwave2Mqtt control panel (see screenshot).  

![image](https://user-images.githubusercontent.com/20862130/63235923-bc3b2e00-c209-11e9-9f6c-a0d88389f2e1.png)

![image](https://user-images.githubusercontent.com/20862130/63235962-e8ef4580-c209-11e9-945b-4b039f5cf0b4.png)

I did not have this issue with the devices in HASS for the last couple of years.  I have 3 of these and they are all doing the same.  I found this while using the HASS Discovery option.  So far the ZW100 devices are working well in HASS.

Here is the HASS Device JSON from the control panel:

```
{
  "type": "sensor",
  "object_id": "temperature",
  "discovery_payload": {
    "unit_of_measurement": "F",
    "device_class": "temperature",
    "value_template": "{{ value_json.value }}",
    "state_topic": "zwave/Bunkie/MultiSensor/test/temperature",
    "json_attributes_topic": "zwave/Bunkie/MultiSensor/test/temperature",
    "device": {
      "identifiers": [
        "zwave2mqtt_Bunkie-MultiSensor"
      ],
      "manufacturer": "AEON Labs",
      "model": "0x0064",
      "name": "ZW100 MultiSensor 6",
      "sw_version": "1.07"
    },
    "name": "Bunkie-MultiSensor_temperature",
    "unique_id": "zwave2mqtt_Bunkie-MultiSensor_3-49-1-1"
  },
  "discoveryTopic": "sensor/Bunkie-MultiSensor/temperature/config",
  "values": [
    "49-1-1"
  ],
  "persistent": false,
  "id": "sensor_temperature"
}
```

My other 2 devices have `"sw_version": "1.08"`

I have searched around on the web but have not found anything.

Let me know if there is anything else I can provide.

Thanks

**Comment by robertsLando** [comment] 2019-08-19 07:00
Did you changed that setting on runtime? I mean the temperature scale value. When you change that setting you have to remove your device from the network and add it back to get the correct values updated

**Comment by robertsLando** [comment] 2019-08-19 07:01
Anyway this is not a bug with z2m so I'm going to close this. Please try to remove and add your device back to check if the value cahnges the scale

**Closed by robertsLando** 2019-08-19 07:01 UTC
Labels: bug

**Comment by iAutom8** [comment] 2019-08-19 17:07
Thanks, I will give that a try.
