### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by sirsiegfrieds** [OpenZWave/Zwave2Mqtt#785] opened 2020-10-13 07:57 UTC
**Version**

Build/Run method
- [x ] Docker

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.6.1280

**Describe the bug**
Hey there, i'm using a fibaro fgs-212 for automate an heater, 
It's works fine 50% , but sometimes it's going down and it's spamming in logs somethings like that : 

```
GET / 304 4.992 ms - -

GET /static/css/app.49d9e97656a80838335d.css 304 1.417 ms - -

GET /static/js/app.1f846484a521ad4911ec.js 304 0.837 ms - -

  z2m:App New connection RsKN6FlZyADXeP9YAAAC +15h

GET /static/logo.png 304 0.441 ms - -

GET /static/fonts/MaterialIcons-Regular.fa3334f.woff2 304 6.916 ms - -

  z2m:Mqtt Message received on zwave2mqtt/ZRL01/37/1/0/set +3m

2020-10-13 09:56:32.205 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Set (Node=5): 0x01, 0x0a, 0x00, 0x13, 0x05, 0x03, 0x25, 0x01, 0xff, 0x25, 0x8c, 0x92"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +3m

2020-10-13 09:56:33.205 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Get (Node=5): 0x01, 0x09, 0x00, 0x13, 0x05, 0x02, 0x25, 0x02, 0x25, 0x8d, 0x6d"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +1s

  z2m:App User disconnected RsKN6FlZyADXeP9YAAAC +2m

  z2m:Mqtt Message received on zwave2mqtt/ZRL01/37/1/0/set +26s

2020-10-13 09:56:57.800 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Set (Node=5): 0x01, 0x0a, 0x00, 0x13, 0x05, 0x03, 0x25, 0x01, 0xff, 0x25, 0x8e, 0x90"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +25s

  z2m:Mqtt Message received on zwave2mqtt/ZRL01/37/1/0/set +1s

2020-10-13 09:56:58.801 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Get (Node=5): 0x01, 0x09, 0x00, 0x13, 0x05, 0x02, 0x25, 0x02, 0x25, 0x8f, 0x6f"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +1s

2020-10-13 09:56:59.801 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Set (Node=5): 0x01, 0x0a, 0x00, 0x13, 0x05, 0x03, 0x25, 0x01, 0xff, 0x25, 0x90, 0x8e"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +1s

2020-10-13 09:57:00.801 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Get (Node=5): 0x01, 0x09, 0x00, 0x13, 0x05, 0x02, 0x25, 0x02, 0x25, 0x91, 0x71"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +1s

```

When the problem is here, no device are working .
Sorry for my english, i'm french :).

**Comment by sirsiegfrieds** [comment] 2020-10-13 08:56
I have reproduced the errors changing température on a climate ( in home assistant )

```
GET / 304 17.400 ms - -

GET /static/js/app.1f846484a521ad4911ec.js 304 3.273 ms - -

GET /static/css/app.49d9e97656a80838335d.css 304 2.100 ms - -

  z2m:App New connection e3sWbzGFr03HZCp5AAAA +5m

GET /static/logo.png 304 0.675 ms - -

GET /static/fonts/MaterialIcons-Regular.fa3334f.woff2 304 10.703 ms - -

  z2m:Mqtt Message received on zwave2mqtt/ZRL01/37/1/0/set +5m

  z2m:Zwave zwave node 5: changed: 37-1-0:Instance 1: Switch:true -> false +5m

  z2m:Mqtt Message received on zwave2mqtt/ZRL01/37/1/0/set +2s

  z2m:Zwave zwave node 5: changed: 37-1-0:Instance 1: Switch:false -> true +2s

  z2m:Mqtt Message received on zwave2mqtt/ZRL01/37/1/0/set +2m

2020-10-13 10:53:20.201 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Set (Node=5): 0x01, 0x0a, 0x00, 0x13, 0x05, 0x03, 0x25, 0x01, 0xff, 0x25, 0x4a, 0x54"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +2m

2020-10-13 10:53:21.205 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Get (Node=5): 0x01, 0x09, 0x00, 0x13, 0x05, 0x02, 0x25, 0x02, 0x25, 0x4b, 0xab"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +1s

  z2m:App Zwave api call: refreshNeighborns [] +3m

  z2m:Zwave Success zwave api call refreshNeighborns [

  undefined,

  [ 5, 8, 9 ],

  undefined,

  undefined,

  undefined,

  [ 1, 8, 9 ],

  [],

  undefined,

  [ 1, 5, 9 ],

  [

    12, 19, 20, 30, 31, 33, 35,

    36, 42, 49, 58, 61, 62, 66,

    73, 78, 82, 85, 86

  ]

] +21s

GET /api/settings 200 66.000 ms - 50337

  z2m:Mqtt Message received on zwave2mqtt/ZRL01/37/1/0/set +1m

2020-10-13 10:54:40.810 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Set (Node=5): 0x01, 0x0a, 0x00, 0x13, 0x05, 0x03, 0x25, 0x01, 0x00, 0x25, 0x4c, 0xad"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +59s

  z2m:Mqtt Message received on zwave2mqtt/ZRL01/37/1/0/set +1s

2020-10-13 10:54:41.810 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Get (Node=5): 0x01, 0x09, 0x00, 0x13, 0x05, 0x02, 0x25, 0x02, 0x25, 0x4d, 0xad"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +1s

2020-10-13 10:54:42.811 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Set (Node=5): 0x01, 0x0a, 0x00, 0x13, 0x05, 0x03, 0x25, 0x01, 0x00, 0x25, 0x4e, 0xaf"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +1s

2020-10-13 10:54:43.811 Error, Node005, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Get (Node=5): 0x01, 0x09, 0x00, 0x13, 0x05, 0x02, 0x25, 0x02, 0x25, 0x4f, 0xaf"

  z2m:Zwave Notification from node 5: Notification - TimeOut (1) +1s
```

That's the starting of the error 👎🏻

**Comment by robertsLando** [comment] 2020-10-13 09:21
@sirsiegfrieds The problem is not z2m related, it could be something with your device or a bug in openzwave library

**Comment by sirsiegfrieds** [comment] 2020-10-13 09:45
in my vm i have those bug 👍🏻 
https://media.discordapp.net/attachments/699736270284390420/765504372267941938/unknown.png

I have changed something and i will try

**Comment by sirsiegfrieds** [comment] 2020-10-13 10:27
Problem still here, i'm gonna call help on a debian forum thanks ...

**Comment by robertsLando** [comment] 2020-10-15 07:34
Let me know if there are any updates here, closing this for now as it's not z2m related

**Closed by robertsLando** 2020-10-15 07:34 UTC
Labels: bug
